name: GitHub Actions Demo
on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: 6 15 * * SUN
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        required: true
jobs: 
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "event: ${{github.event_name}}"
          echo "branch: ${{github.ref}}"
      - uses: actions/checkout@v3.3.0
      - run: |
          echo "files"
          tree
  Test:
    runs-on: ubuntu-latest
    needs: Build
    if: github.event_name == 'workflow_dispatch'
    environment: Test
    steps:
      - run: echo "Testing..."
  Load-Test:
    runs-on: ubuntu-latest
    needs: Build
    if: github.event_name == 'workflow_dispatch'
    environment: Load-Test
    steps: |
      echo "Testing..."
      sleep 15
  Production:
    runs-on: ubuntu-latest
    needs: [Test, Load-Test]
    environment: 
      name: Production
      url: https://writeabout.net
    if: github.event.inputs.environment == 'Production'
    steps:
      - run: |
          echo "Step 1 deploying..."
          sleep 10
      - run: |
          echo "Step 2 deploying..."
          sleep 10
      - run: |
          echo "Step 3 deploying..."
          sleep 10
      - run: |
          echo "Step 4 deploying..."
          sleep 10
      - run: |
          echo "Step 5 deploying..."
          sleep 10
    
    
  
      
      
      

